// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationsAPI.Database;

namespace NationsAPI.Migrations
{
    [DbContext(typeof(NationsDbContext))]
    partial class NationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);


            modelBuilder.Entity("NationsAPI.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<long?>("FromPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ToPlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromPlayerId");

                    b.HasIndex("ToPlayerId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("NationsAPI.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nick")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nick = "settler",
                            Password = "YsiwFeSpgAA0qnBxQVqfJxsUxSPLHBKinJuFr89QJ8iPIBHk"
                        });
                });

            modelBuilder.Entity("NationsAPI.Models.Message", b =>
                {
                    b.HasOne("NationsAPI.Models.Player", "FromPlayer")
                        .WithMany("MessageFromPlayers")
                        .HasForeignKey("FromPlayerId")
                        .HasConstraintName("FK__Message__FromPlayer__2180FB33");

                    b.HasOne("NationsAPI.Models.Player", "ToPlayer")
                        .WithMany("MessageToPlayers")
                        .HasForeignKey("ToPlayerId")
                        .HasConstraintName("FK__Message__ToPlayer__208CD6FA");

                    b.Navigation("FromPlayer");

                    b.Navigation("ToPlayer");
                });

            modelBuilder.Entity("NationsAPI.Models.Player", b =>
                {
                    b.Navigation("MessageFromPlayers");

                    b.Navigation("MessageToPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
